// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// ValidateStruct provides a mock function with given fields: val
func (_m *Service) ValidateStruct(val interface{}) error {
	ret := _m.Called(val)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(val)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateStructWithContext provides a mock function with given fields: ctx, val
func (_m *Service) ValidateStructWithContext(ctx context.Context, val interface{}) error {
	ret := _m.Called(ctx, val)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, val)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateStructWithLang provides a mock function with given fields: lang, val
func (_m *Service) ValidateStructWithLang(lang string, val interface{}) error {
	ret := _m.Called(lang, val)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(lang, val)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
